name: Build and deploy
run-name: Build ${{ github.run_number }}
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build and deploy triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} server"
      - run: echo "Branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - run: ./scripts/build.sh $PWD $PWD/dist https://raw.githubusercontent.com/rileydog16/tools-release/main
      - name: List files in the repository
        run: |
          ls -lR ${{ github.workspace }}
      - run: npm install
      - run: ./scripts/deploy.sh

